"""fixed

Revision ID: 168c8204706a
Revises: e503c98861fb
Create Date: 2026-02-24 21:19:22.251890

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "168c8204706a"
down_revision: Union[str, Sequence[str], None] = "e503c98861fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game_sessions", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "users_data", ["user_id"], ["tg_id"])

    with op.batch_alter_table("games_history", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "users_data", ["user_id"], ["tg_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("games_history", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "users_data", ["user_id"], ["id"])

    with op.batch_alter_table("game_sessions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "users_data", ["user_id"], ["id"])
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###
