"""upgrade

Revision ID: 34325f04668d
Revises: 6ecf2d710ef7
Create Date: 2026-02-21 01:59:20.828939

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "34325f04668d"
down_revision: Union[str, Sequence[str], None] = "6ecf2d710ef7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tg_id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tg_id"),
    )
    op.create_table(
        "games_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("game_type", sa.String(), nullable=False),
        sa.Column("game_result", sa.Boolean(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_data.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("game_history")
    op.drop_constraint(None, "game_sessions", type_="foreignkey")
    op.create_foreign_key(None, "game_sessions", "users_data", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "game_sessions", type_="foreignkey")
    op.create_foreign_key(None, "game_sessions", "user_data", ["user_id"], ["id"])
    op.create_table(
        "game_history",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("game_type", sa.VARCHAR(), nullable=False),
        sa.Column("game_result", sa.BOOLEAN(), nullable=False),
        sa.Column("chat_id", sa.INTEGER(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_data.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("games_history")
    op.drop_table("users_data")
    # ### end Alembic commands ###
