"""upgrade

Revision ID: 48fb8cb264f1
Revises: e2801a65e839
Create Date: 2026-02-21 11:46:54.108890

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48fb8cb264f1"
down_revision: Union[str, Sequence[str], None] = "e2801a65e839"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game_sessions", sa.Column("chat_id", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "game_sessions", ["chat_id"])
    op.alter_column(
        "quiz_questions", "word", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "quiz_questions", "definition", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quiz_questions", "definition", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column("quiz_questions", "word", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_constraint(None, "game_sessions", type_="unique")
    op.drop_column("game_sessions", "chat_id")
    # ### end Alembic commands ###
