"""upgrade

Revision ID: b3c037aa2f3a
Revises: 48fb8cb264f1
Create Date: 2026-02-21 11:50:07.008059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c037aa2f3a'
down_revision: Union[str, Sequence[str], None] = '48fb8cb264f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions') as batch_op:
        batch_op.create_unique_constraint('uq_game_sessions_chat_id', ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions') as batch_op:
        batch_op.drop_constraint('uq_game_sessions_chat_id', type_='unique')
    # ### end Alembic commands ###
